services:
  web:
    image: ghcr.io/tomas-gen/web_flama:latest
    container_name: web_flama
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "3016:3000"
    environment:
      - NEXT_PUBLIC_PHONE_DISPLAY=+54 9 2634 73-9193
      - NEXT_PUBLIC_PHONE_INTERNATIONAL=+5492634739193
      - NEXT_PUBLIC_WHATSAPP_ID=5492634739193
      - NEXT_PUBLIC_ADDRESS=Ladislao Segura 190, M5573 Junín, Mendoza
      - NEXT_PUBLIC_INSTAGRAM=flamastudio.ar
      - NEXT_PUBLIC_MAPS_URL=https://maps.app.goo.gl/tDXcngSKQLuvmzuZ7
      - NEXT_PUBLIC_HOURS=Lun a Vie, 9:30–17:30
    restart: unless-stopped
